//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TurnosWPF
{
    using System;
    using System.Collections.Generic;
    
    public partial class ticket
    {
        public long id { get; set; }
        public string codigo { get; set; }
        public string codigo_numeracion { get; set; }
        public Nullable<int> modulo { get; set; }
        public Nullable<int> estado { get; set; }
        public string creado_por { get; set; }
    }
}
